<?php

namespace App\Services\Calling;

use App\Models\ApiConnection;
use App\Models\WhatsappCall;

interface WhatsappCallServiceInterface
{
    /**
     * Place an outbound WhatsApp call for the given WhatsappCall record using
     * a real SDP offer generated by the caller's WebRTC peer connection, and
     * return Meta's call ID (used later to match webhook status updates back
     * to this call), mirroring VoiceCallServiceInterface::placeCall().
     */
    public function placeCall(WhatsappCall $call, ApiConnection $connection, string $sdpOffer): string;

    /**
     * Send a call action (e.g. speak a prompt / pre-accept / terminate) to
     * Meta's Calling API for an in-progress call.
     */
    public function sendCallAction(WhatsappCall $call, ApiConnection $connection, array $action): void;

    /**
     * Send Meta's in-chat "call permission request" message so the contact
     * can opt in to receiving calls from this business (required before
     * placeCall() will succeed — Meta rejects with code 138006/2593090
     * otherwise).
     */
    public function sendCallPermissionRequest(WhatsappCall $call, ApiConnection $connection): void;
}
